//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FinLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FinLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Finance.Resources.FinLang", typeof(FinLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About_Text {
            get {
                return ResourceManager.GetString("About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date format can be changed in the settings to the international standard format ISO 8601 (YYYY-MM-DD).
        ///
        ///The method of rounding can lead to deviations from the final result (for example in the last installment of loans).
        ///The numbers are rounded to the nearest cent by default (arithmetic: 1-4 down and 5-9 up).
        ///Can be changed to even number (banker&apos;s rounding) 1-4 down, 6-9 up and 5 on even number down, odd number up.
        ///
        ///Google Translate was used for the translation of the text. This is not a guarantee [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutExplanation_Text {
            get {
                return ResourceManager.GetString("AboutExplanation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        internal static string Agree_Text {
            get {
                return ResourceManager.GetString("Agree_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost amount:.
        /// </summary>
        internal static string AmountCost_Text {
            get {
                return ResourceManager.GetString("AmountCost_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount difference:.
        /// </summary>
        internal static string AmountDifference_Text {
            get {
                return ResourceManager.GetString("AmountDifference_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount gross:.
        /// </summary>
        internal static string AmountGross_Text {
            get {
                return ResourceManager.GetString("AmountGross_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate amount gross from amount net and percentage..
        /// </summary>
        internal static string AmountGrossOfNetExplanation_Text {
            get {
                return ResourceManager.GetString("AmountGrossOfNetExplanation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount gross of net amount.
        /// </summary>
        internal static string AmountGrossOfNetForm_Text {
            get {
                return ResourceManager.GetString("AmountGrossOfNetForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount net:.
        /// </summary>
        internal static string AmountNet_Text {
            get {
                return ResourceManager.GetString("AmountNet_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount per period:.
        /// </summary>
        internal static string AmountPeriod_Text {
            get {
                return ResourceManager.GetString("AmountPeriod_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase amount:.
        /// </summary>
        internal static string AmountPurchase_Text {
            get {
                return ResourceManager.GetString("AmountPurchase_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue per year:.
        /// </summary>
        internal static string AmountRevenueYear_Text {
            get {
                return ResourceManager.GetString("AmountRevenueYear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount:.
        /// </summary>
        internal static string AmountTotal_Text {
            get {
                return ResourceManager.GetString("AmountTotal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ButtonClose_Text {
            get {
                return ResourceManager.GetString("ButtonClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string Calculate_Text {
            get {
                return ResourceManager.GetString("Calculate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final capital:.
        /// </summary>
        internal static string CapitalFinal_Text {
            get {
                return ResourceManager.GetString("CapitalFinal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial capital:.
        /// </summary>
        internal static string CapitalInitial_Text {
            get {
                return ResourceManager.GetString("CapitalInitial_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital + interest:.
        /// </summary>
        internal static string CapitalInterest_Text {
            get {
                return ResourceManager.GetString("CapitalInterest_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Clear_Text {
            get {
                return ResourceManager.GetString("Clear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        internal static string Contact_Text {
            get {
                return ResourceManager.GetString("Contact_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string Copyright_Text {
            get {
                return ResourceManager.GetString("Copyright_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency code:.
        /// </summary>
        internal static string CurrencyCode_Text {
            get {
                return ResourceManager.GetString("CurrencyCode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Dark_Text {
            get {
                return ResourceManager.GetString("Dark_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date 1:.
        /// </summary>
        internal static string Date1_Text {
            get {
                return ResourceManager.GetString("Date1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date 2:.
        /// </summary>
        internal static string Date2_Text {
            get {
                return ResourceManager.GetString("Date2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date difference in days:.
        /// </summary>
        internal static string DateDifferenceDays_Text {
            get {
                return ResourceManager.GetString("DateDifferenceDays_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = hours:.
        /// </summary>
        internal static string DateDifferenceHours_Text {
            get {
                return ResourceManager.GetString("DateDifferenceHours_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = minutes:.
        /// </summary>
        internal static string DateDifferenceMinutes_Text {
            get {
                return ResourceManager.GetString("DateDifferenceMinutes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = seconds:.
        /// </summary>
        internal static string DateDifferenceSeconds_Text {
            get {
                return ResourceManager.GetString("DateDifferenceSeconds_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date first repayment:.
        /// </summary>
        internal static string DateFirstRepayment_Text {
            get {
                return ResourceManager.GetString("DateFirstRepayment_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date format:.
        /// </summary>
        internal static string DateFormat_Text {
            get {
                return ResourceManager.GetString("DateFormat_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO 8601.
        /// </summary>
        internal static string DateISO8601_Text {
            get {
                return ResourceManager.GetString("DateISO8601_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End month:.
        /// </summary>
        internal static string DayEndMonth_Text {
            get {
                return ResourceManager.GetString("DayEndMonth_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default_Text {
            get {
                return ResourceManager.GetString("Default_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial applications.
        /// </summary>
        internal static string Description_Text {
            get {
                return ResourceManager.GetString("Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string Detail_Text {
            get {
                return ResourceManager.GetString("Detail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference between dates.
        /// </summary>
        internal static string DifferenceDatesForm_Text {
            get {
                return ResourceManager.GetString("DifferenceDatesForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate the difference between two dates..
        /// </summary>
        internal static string DifferenceExplanationDates_Text {
            get {
                return ResourceManager.GetString("DifferenceExplanationDates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate the difference between two numbers..
        /// </summary>
        internal static string DifferenceExplanationNumbers_Text {
            get {
                return ResourceManager.GetString("DifferenceExplanationNumbers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference between numbers.
        /// </summary>
        internal static string DifferenceNumbersForm_Text {
            get {
                return ResourceManager.GetString("DifferenceNumbersForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disagree.
        /// </summary>
        internal static string Disagree_Text {
            get {
                return ResourceManager.GetString("Disagree_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration in months:.
        /// </summary>
        internal static string DurationMonths_Text {
            get {
                return ResourceManager.GetString("DurationMonths_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration in years:.
        /// </summary>
        internal static string DurationYears_Text {
            get {
                return ResourceManager.GetString("DurationYears_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        internal static string Email_Text {
            get {
                return ResourceManager.GetString("Email_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address?.
        /// </summary>
        internal static string EmailAddressQuestion_Text {
            get {
                return ResourceManager.GetString("EmailAddressQuestion_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached the detail of the loan..
        /// </summary>
        internal static string EmailBody_Text {
            get {
                return ResourceManager.GetString("EmailBody_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not yet fully supported in Windows.
        ///The created file must be manually attached to the e-mail..
        /// </summary>
        internal static string EmailMessage_Text {
            get {
                return ResourceManager.GetString("EmailMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send this document to an e-mail address?.
        /// </summary>
        internal static string EmailSendQuestion_Text {
            get {
                return ResourceManager.GetString("EmailSendQuestion_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance - Detail of the loan.
        /// </summary>
        internal static string EmailSubject_Text {
            get {
                return ResourceManager.GetString("EmailSubject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string EmailTitle_Text {
            get {
                return ResourceManager.GetString("EmailTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle_Text {
            get {
                return ResourceManager.GetString("ErrorTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry days with discount:.
        /// </summary>
        internal static string ExpiryDaysWithDiscount_Text {
            get {
                return ResourceManager.GetString("ExpiryDaysWithDiscount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry days without discount:.
        /// </summary>
        internal static string ExpiryDaysWithoutDiscount_Text {
            get {
                return ResourceManager.GetString("ExpiryDaysWithoutDiscount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ExportFile_Text {
            get {
                return ResourceManager.GetString("ExportFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount gross of net amount.
        /// </summary>
        internal static string FinanceAmountGrossOfNet_Text {
            get {
                return ResourceManager.GetString("FinanceAmountGrossOfNet_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference between dates.
        /// </summary>
        internal static string FinanceDifferenceDates_Text {
            get {
                return ResourceManager.GetString("FinanceDifferenceDates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference between numbers.
        /// </summary>
        internal static string FinanceDifferenceNumbers_Text {
            get {
                return ResourceManager.GetString("FinanceDifferenceNumbers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        internal static string FinanceForm_Text {
            get {
                return ResourceManager.GetString("FinanceForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual interest starting amount.
        /// </summary>
        internal static string FinanceInterestAnnual_Text {
            get {
                return ResourceManager.GetString("FinanceInterestAnnual_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective interest.
        /// </summary>
        internal static string FinanceInterestEffective_Text {
            get {
                return ResourceManager.GetString("FinanceInterestEffective_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective interest start and end amount.
        /// </summary>
        internal static string FinanceInterestEffectiveBE_Text {
            get {
                return ResourceManager.GetString("FinanceInterestEffectiveBE_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest per month and per day.
        /// </summary>
        internal static string FinanceInterestMonthDay_Text {
            get {
                return ResourceManager.GetString("FinanceInterestMonthDay_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest payment discount.
        /// </summary>
        internal static string FinanceInterestPayDiscount_Text {
            get {
                return ResourceManager.GetString("FinanceInterestPayDiscount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return on investment.
        /// </summary>
        internal static string FinanceInvestmentReturn_Text {
            get {
                return ResourceManager.GetString("FinanceInvestmentReturn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan with amortization table.
        /// </summary>
        internal static string FinanceLoanDetail_Text {
            get {
                return ResourceManager.GetString("FinanceLoanDetail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT calculations.
        /// </summary>
        internal static string FinanceVATCalculation_Text {
            get {
                return ResourceManager.GetString("FinanceVATCalculation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate the interest per year.
        ///
        ///Enter the starting amount, the term in months, and either the amount per term or the final amount..
        /// </summary>
        internal static string InterestAnnualExplanation_Text {
            get {
                return ResourceManager.GetString("InterestAnnualExplanation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual interest.
        /// </summary>
        internal static string InterestAnnualForm_Text {
            get {
                return ResourceManager.GetString("InterestAnnualForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily interest (365 days/year):.
        /// </summary>
        internal static string InterestDay365_Text {
            get {
                return ResourceManager.GetString("InterestDay365_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily interest (366 days/year):.
        /// </summary>
        internal static string InterestDay366_Text {
            get {
                return ResourceManager.GetString("InterestDay366_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective interest:.
        /// </summary>
        internal static string InterestEffective_Text {
            get {
                return ResourceManager.GetString("InterestEffective_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The effective interest rate for a loan with a known beginning and end amount..
        /// </summary>
        internal static string InterestEffectiveBEExplanation_Text {
            get {
                return ResourceManager.GetString("InterestEffectiveBEExplanation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest with start and end amount.
        /// </summary>
        internal static string InterestEffectiveBEForm_Text {
            get {
                return ResourceManager.GetString("InterestEffectiveBEForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting the nominal interest rate to the effective interest rate..
        /// </summary>
        internal static string InterestEffectiveExplanation_Text {
            get {
                return ResourceManager.GetString("InterestEffectiveExplanation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective interest.
        /// </summary>
        internal static string InterestEffectiveForm_Text {
            get {
                return ResourceManager.GetString("InterestEffectiveForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly interest:.
        /// </summary>
        internal static string InterestMonth_Text {
            get {
                return ResourceManager.GetString("InterestMonth_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate the fixed interest per month and per day..
        /// </summary>
        internal static string InterestMonthDayExplanation_Text {
            get {
                return ResourceManager.GetString("InterestMonthDayExplanation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest per month and per day.
        /// </summary>
        internal static string InterestMonthDayForm_Text {
            get {
                return ResourceManager.GetString("InterestMonthDayForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate the effective interest for a payment discount..
        /// </summary>
        internal static string InterestPayDiscountExplanation_Text {
            get {
                return ResourceManager.GetString("InterestPayDiscountExplanation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest payment discount.
        /// </summary>
        internal static string InterestPayDiscountForm_Text {
            get {
                return ResourceManager.GetString("InterestPayDiscountForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual interest:.
        /// </summary>
        internal static string InterestRate_Text {
            get {
                return ResourceManager.GetString("InterestRate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total interest:.
        /// </summary>
        internal static string InterestTotal_Text {
            get {
                return ResourceManager.GetString("InterestTotal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return in percentages per year on investment:
        ///Enter the purchase amount (+ the amount of costs) and the amount of the revenue per year.
        ///
        ///Calculating the amount of the investment:
        ///Enter the amount of the yield per year and the desired yield in percentage..
        /// </summary>
        internal static string InvestmentReturnExplanation_Text {
            get {
                return ResourceManager.GetString("InvestmentReturnExplanation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return on investment.
        /// </summary>
        internal static string InvestmentReturnForm_Text {
            get {
                return ResourceManager.GetString("InvestmentReturnForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard:.
        /// </summary>
        internal static string Keyboard_Text {
            get {
                return ResourceManager.GetString("Keyboard_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string Language_de_Text {
            get {
                return ResourceManager.GetString("Language_de_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language_en_Text {
            get {
                return ResourceManager.GetString("Language_en_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string Language_es_Text {
            get {
                return ResourceManager.GetString("Language_es_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string Language_fr_Text {
            get {
                return ResourceManager.GetString("Language_fr_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string Language_it_Text {
            get {
                return ResourceManager.GetString("Language_it_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        internal static string Language_nl_Text {
            get {
                return ResourceManager.GetString("Language_nl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        internal static string Language_pt_Text {
            get {
                return ResourceManager.GetString("Language_pt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language_Text {
            get {
                return ResourceManager.GetString("Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application may be used freely for non-commercial purposes.
        ///Use this program entirely at your own risk..
        /// </summary>
        internal static string License_Text {
            get {
                return ResourceManager.GetString("License_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you agree with the license conditions?.
        /// </summary>
        internal static string LicenseAgreement_Text {
            get {
                return ResourceManager.GetString("LicenseAgreement_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The software is provided &apos;as is&apos;, without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the author and/or publisher be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the software or the use or other dealings in the software..
        /// </summary>
        internal static string LicenseMit2_Text {
            get {
                return ResourceManager.GetString("LicenseMit2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string LicenseTitle_Text {
            get {
                return ResourceManager.GetString("LicenseTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light_Text {
            get {
                return ResourceManager.GetString("Light_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan annuities.
        /// </summary>
        internal static string LoanAnnuity_Text {
            get {
                return ResourceManager.GetString("LoanAnnuity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string LoanDetailColumns_0_Text {
            get {
                return ResourceManager.GetString("LoanDetailColumns_0_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        internal static string LoanDetailColumns_1_Text {
            get {
                return ResourceManager.GetString("LoanDetailColumns_1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To pay.
        /// </summary>
        internal static string LoanDetailColumns_2_Text {
            get {
                return ResourceManager.GetString("LoanDetailColumns_2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital.
        /// </summary>
        internal static string LoanDetailColumns_3_Text {
            get {
                return ResourceManager.GetString("LoanDetailColumns_3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest.
        /// </summary>
        internal static string LoanDetailColumns_4_Text {
            get {
                return ResourceManager.GetString("LoanDetailColumns_4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total interest.
        /// </summary>
        internal static string LoanDetailColumns_5_Text {
            get {
                return ResourceManager.GetString("LoanDetailColumns_5_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining capital.
        /// </summary>
        internal static string LoanDetailColumns_6_Text {
            get {
                return ResourceManager.GetString("LoanDetailColumns_6_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amortization table annuity loan.
        /// </summary>
        internal static string LoanDetailDocTitleAnnuity_Text {
            get {
                return ResourceManager.GetString("LoanDetailDocTitleAnnuity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amortization table linear loan.
        /// </summary>
        internal static string LoanDetailDocTitleLinear_Text {
            get {
                return ResourceManager.GetString("LoanDetailDocTitleLinear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinanceDocument.
        /// </summary>
        internal static string LoanDetailDocumentName_Text {
            get {
                return ResourceManager.GetString("LoanDetailDocumentName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuities or linear loan with amortization table..
        /// </summary>
        internal static string LoanDetailExplanation_Text {
            get {
                return ResourceManager.GetString("LoanDetailExplanation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p.
        /// </summary>
        internal static string LoanDetailFirstLetterPeriod_Text {
            get {
                return ResourceManager.GetString("LoanDetailFirstLetterPeriod_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        internal static string LoanDetailFirstLetterYear_Text {
            get {
                return ResourceManager.GetString("LoanDetailFirstLetterYear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan with amortization table.
        /// </summary>
        internal static string LoanDetailForm_Text {
            get {
                return ResourceManager.GetString("LoanDetailForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear loan.
        /// </summary>
        internal static string LoanLinear_Text {
            get {
                return ResourceManager.GetString("LoanLinear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan type:.
        /// </summary>
        internal static string Loantype_Text {
            get {
                return ResourceManager.GetString("Loantype_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        internal static string NameProgram_Text {
            get {
                return ResourceManager.GetString("NameProgram_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No_Text {
            get {
                return ResourceManager.GetString("No_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of decimals:.
        /// </summary>
        internal static string NumDec_Text {
            get {
                return ResourceManager.GetString("NumDec_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        internal static string Numeric_Text {
            get {
                return ResourceManager.GetString("Numeric_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A4.
        /// </summary>
        internal static string PageA4_Text {
            get {
                return ResourceManager.GetString("PageA4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page format:.
        /// </summary>
        internal static string PageFormat_Text {
            get {
                return ResourceManager.GetString("PageFormat_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        internal static string PageLetter_Text {
            get {
                return ResourceManager.GetString("PageLetter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment discount:.
        /// </summary>
        internal static string PaymentDiscount_Text {
            get {
                return ResourceManager.GetString("PaymentDiscount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage:.
        /// </summary>
        internal static string Percentage_Text {
            get {
                return ResourceManager.GetString("Percentage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return per year:.
        /// </summary>
        internal static string PercentageReturnYear_Text {
            get {
                return ResourceManager.GetString("PercentageReturnYear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods per year:.
        /// </summary>
        internal static string PeriodsYear_Text {
            get {
                return ResourceManager.GetString("PeriodsYear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print_Text {
            get {
                return ResourceManager.GetString("Print_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No personal and other data is stored or passed on to myself and others..
        /// </summary>
        internal static string PrivacyPolicy_Text {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy:.
        /// </summary>
        internal static string PrivacyPolicyTitle_Text {
            get {
                return ResourceManager.GetString("PrivacyPolicyTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset_Text {
            get {
                return ResourceManager.GetString("Reset_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounding of number:.
        /// </summary>
        internal static string RoundNumber_Text {
            get {
                return ResourceManager.GetString("RoundNumber_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arithmetic.
        /// </summary>
        internal static string RoundNumberAwayFromZero_Text {
            get {
                return ResourceManager.GetString("RoundNumberAwayFromZero_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To even number.
        /// </summary>
        internal static string RoundNumberToEven_Text {
            get {
                return ResourceManager.GetString("RoundNumberToEven_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save_Text {
            get {
                return ResourceManager.GetString("Save_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Text {
            get {
                return ResourceManager.GetString("Settings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this document?.
        /// </summary>
        internal static string ShareQuestion_Text {
            get {
                return ResourceManager.GetString("ShareQuestion_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string System_Text {
            get {
                return ResourceManager.GetString("System_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text_Text {
            get {
                return ResourceManager.GetString("Text_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        internal static string Theme_Text {
            get {
                return ResourceManager.GetString("Theme_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The theme will not be applied until the application is closed.
        ///Close now?.
        /// </summary>
        internal static string ThemeSave_Text {
            get {
                return ResourceManager.GetString("ThemeSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string ThemeTitle_Text {
            get {
                return ResourceManager.GetString("ThemeTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between the ISO date format and the system date format..
        /// </summary>
        internal static string ToolTipDateFormat_Text {
            get {
                return ResourceManager.GetString("ToolTipDateFormat_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 1:.
        /// </summary>
        internal static string Value1_Text {
            get {
                return ResourceManager.GetString("Value1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 2:.
        /// </summary>
        internal static string Value2_Text {
            get {
                return ResourceManager.GetString("Value2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value difference:.
        /// </summary>
        internal static string ValueDifference_Text {
            get {
                return ResourceManager.GetString("ValueDifference_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage difference:.
        /// </summary>
        internal static string ValuePercDifference_Text {
            get {
                return ResourceManager.GetString("ValuePercDifference_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 1 = % value 2:.
        /// </summary>
        internal static string ValuePercDiffValue1_Text {
            get {
                return ResourceManager.GetString("ValuePercDiffValue1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 2 = % value 1:.
        /// </summary>
        internal static string ValuePercDiffValue2_Text {
            get {
                return ResourceManager.GetString("ValuePercDiffValue2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount VAT:.
        /// </summary>
        internal static string VATAmount_Text {
            get {
                return ResourceManager.GetString("VATAmount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount VAT exclusive:.
        /// </summary>
        internal static string VATAmountExclusive_Text {
            get {
                return ResourceManager.GetString("VATAmountExclusive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount VAT included:.
        /// </summary>
        internal static string VATAmountIncluded_Text {
            get {
                return ResourceManager.GetString("VATAmountIncluded_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate the amount excluding VAT or the amount including VAT..
        /// </summary>
        internal static string VATCalculationExplanation_Text {
            get {
                return ResourceManager.GetString("VATCalculationExplanation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT calculations.
        /// </summary>
        internal static string VATCalculationForm_Text {
            get {
                return ResourceManager.GetString("VATCalculationForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT percentage:.
        /// </summary>
        internal static string VATPercentage_Text {
            get {
                return ResourceManager.GetString("VATPercentage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string Version_Text {
            get {
                return ResourceManager.GetString("Version_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper dimensions too small !.
        /// </summary>
        internal static string WarningPageDimensions_Text {
            get {
                return ResourceManager.GetString("WarningPageDimensions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website:.
        /// </summary>
        internal static string Website_Text {
            get {
                return ResourceManager.GetString("Website_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes_Text {
            get {
                return ResourceManager.GetString("Yes_Text", resourceCulture);
            }
        }
    }
}
